// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WifiScanResult.proto

package org.sas04225.proto;

public final class WifiScanResultProto {
  private WifiScanResultProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WifiScanResultOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string location_tag = 1;
    boolean hasLocationTag();
    String getLocationTag();
    
    // repeated .org.sas04225.AccessPoint result = 2;
    java.util.List<org.sas04225.proto.WifiScanResultProto.AccessPoint> 
        getResultList();
    org.sas04225.proto.WifiScanResultProto.AccessPoint getResult(int index);
    int getResultCount();
    java.util.List<? extends org.sas04225.proto.WifiScanResultProto.AccessPointOrBuilder> 
        getResultOrBuilderList();
    org.sas04225.proto.WifiScanResultProto.AccessPointOrBuilder getResultOrBuilder(
        int index);
  }
  public static final class WifiScanResult extends
      com.google.protobuf.GeneratedMessage
      implements WifiScanResultOrBuilder {
    // Use WifiScanResult.newBuilder() to construct.
    private WifiScanResult(Builder builder) {
      super(builder);
    }
    private WifiScanResult(boolean noInit) {}
    
    private static final WifiScanResult defaultInstance;
    public static WifiScanResult getDefaultInstance() {
      return defaultInstance;
    }
    
    public WifiScanResult getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sas04225.proto.WifiScanResultProto.internal_static_org_sas04225_WifiScanResult_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sas04225.proto.WifiScanResultProto.internal_static_org_sas04225_WifiScanResult_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string location_tag = 1;
    public static final int LOCATION_TAG_FIELD_NUMBER = 1;
    private java.lang.Object locationTag_;
    public boolean hasLocationTag() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getLocationTag() {
      java.lang.Object ref = locationTag_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          locationTag_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLocationTagBytes() {
      java.lang.Object ref = locationTag_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        locationTag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .org.sas04225.AccessPoint result = 2;
    public static final int RESULT_FIELD_NUMBER = 2;
    private java.util.List<org.sas04225.proto.WifiScanResultProto.AccessPoint> result_;
    public java.util.List<org.sas04225.proto.WifiScanResultProto.AccessPoint> getResultList() {
      return result_;
    }
    public java.util.List<? extends org.sas04225.proto.WifiScanResultProto.AccessPointOrBuilder> 
        getResultOrBuilderList() {
      return result_;
    }
    public int getResultCount() {
      return result_.size();
    }
    public org.sas04225.proto.WifiScanResultProto.AccessPoint getResult(int index) {
      return result_.get(index);
    }
    public org.sas04225.proto.WifiScanResultProto.AccessPointOrBuilder getResultOrBuilder(
        int index) {
      return result_.get(index);
    }
    
    private void initFields() {
      locationTag_ = "";
      result_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasLocationTag()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getResultCount(); i++) {
        if (!getResult(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getLocationTagBytes());
      }
      for (int i = 0; i < result_.size(); i++) {
        output.writeMessage(2, result_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getLocationTagBytes());
      }
      for (int i = 0; i < result_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, result_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.sas04225.proto.WifiScanResultProto.WifiScanResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.sas04225.proto.WifiScanResultProto.WifiScanResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.sas04225.proto.WifiScanResultProto.WifiScanResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.sas04225.proto.WifiScanResultProto.WifiScanResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.sas04225.proto.WifiScanResultProto.WifiScanResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.sas04225.proto.WifiScanResultProto.WifiScanResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.sas04225.proto.WifiScanResultProto.WifiScanResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.sas04225.proto.WifiScanResultProto.WifiScanResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.sas04225.proto.WifiScanResultProto.WifiScanResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.sas04225.proto.WifiScanResultProto.WifiScanResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.sas04225.proto.WifiScanResultProto.WifiScanResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.sas04225.proto.WifiScanResultProto.WifiScanResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sas04225.proto.WifiScanResultProto.internal_static_org_sas04225_WifiScanResult_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sas04225.proto.WifiScanResultProto.internal_static_org_sas04225_WifiScanResult_fieldAccessorTable;
      }
      
      // Construct using org.sas04225.proto.WifiScanResultProto.WifiScanResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getResultFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        locationTag_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (resultBuilder_ == null) {
          result_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          resultBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.sas04225.proto.WifiScanResultProto.WifiScanResult.getDescriptor();
      }
      
      public org.sas04225.proto.WifiScanResultProto.WifiScanResult getDefaultInstanceForType() {
        return org.sas04225.proto.WifiScanResultProto.WifiScanResult.getDefaultInstance();
      }
      
      public org.sas04225.proto.WifiScanResultProto.WifiScanResult build() {
        org.sas04225.proto.WifiScanResultProto.WifiScanResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.sas04225.proto.WifiScanResultProto.WifiScanResult buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.sas04225.proto.WifiScanResultProto.WifiScanResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.sas04225.proto.WifiScanResultProto.WifiScanResult buildPartial() {
        org.sas04225.proto.WifiScanResultProto.WifiScanResult result = new org.sas04225.proto.WifiScanResultProto.WifiScanResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.locationTag_ = locationTag_;
        if (resultBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            result_ = java.util.Collections.unmodifiableList(result_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.result_ = result_;
        } else {
          result.result_ = resultBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sas04225.proto.WifiScanResultProto.WifiScanResult) {
          return mergeFrom((org.sas04225.proto.WifiScanResultProto.WifiScanResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.sas04225.proto.WifiScanResultProto.WifiScanResult other) {
        if (other == org.sas04225.proto.WifiScanResultProto.WifiScanResult.getDefaultInstance()) return this;
        if (other.hasLocationTag()) {
          setLocationTag(other.getLocationTag());
        }
        if (resultBuilder_ == null) {
          if (!other.result_.isEmpty()) {
            if (result_.isEmpty()) {
              result_ = other.result_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureResultIsMutable();
              result_.addAll(other.result_);
            }
            onChanged();
          }
        } else {
          if (!other.result_.isEmpty()) {
            if (resultBuilder_.isEmpty()) {
              resultBuilder_.dispose();
              resultBuilder_ = null;
              result_ = other.result_;
              bitField0_ = (bitField0_ & ~0x00000002);
              resultBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getResultFieldBuilder() : null;
            } else {
              resultBuilder_.addAllMessages(other.result_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasLocationTag()) {
          
          return false;
        }
        for (int i = 0; i < getResultCount(); i++) {
          if (!getResult(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              locationTag_ = input.readBytes();
              break;
            }
            case 18: {
              org.sas04225.proto.WifiScanResultProto.AccessPoint.Builder subBuilder = org.sas04225.proto.WifiScanResultProto.AccessPoint.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addResult(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string location_tag = 1;
      private java.lang.Object locationTag_ = "";
      public boolean hasLocationTag() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getLocationTag() {
        java.lang.Object ref = locationTag_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          locationTag_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLocationTag(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        locationTag_ = value;
        onChanged();
        return this;
      }
      public Builder clearLocationTag() {
        bitField0_ = (bitField0_ & ~0x00000001);
        locationTag_ = getDefaultInstance().getLocationTag();
        onChanged();
        return this;
      }
      void setLocationTag(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        locationTag_ = value;
        onChanged();
      }
      
      // repeated .org.sas04225.AccessPoint result = 2;
      private java.util.List<org.sas04225.proto.WifiScanResultProto.AccessPoint> result_ =
        java.util.Collections.emptyList();
      private void ensureResultIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          result_ = new java.util.ArrayList<org.sas04225.proto.WifiScanResultProto.AccessPoint>(result_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.sas04225.proto.WifiScanResultProto.AccessPoint, org.sas04225.proto.WifiScanResultProto.AccessPoint.Builder, org.sas04225.proto.WifiScanResultProto.AccessPointOrBuilder> resultBuilder_;
      
      public java.util.List<org.sas04225.proto.WifiScanResultProto.AccessPoint> getResultList() {
        if (resultBuilder_ == null) {
          return java.util.Collections.unmodifiableList(result_);
        } else {
          return resultBuilder_.getMessageList();
        }
      }
      public int getResultCount() {
        if (resultBuilder_ == null) {
          return result_.size();
        } else {
          return resultBuilder_.getCount();
        }
      }
      public org.sas04225.proto.WifiScanResultProto.AccessPoint getResult(int index) {
        if (resultBuilder_ == null) {
          return result_.get(index);
        } else {
          return resultBuilder_.getMessage(index);
        }
      }
      public Builder setResult(
          int index, org.sas04225.proto.WifiScanResultProto.AccessPoint value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultIsMutable();
          result_.set(index, value);
          onChanged();
        } else {
          resultBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setResult(
          int index, org.sas04225.proto.WifiScanResultProto.AccessPoint.Builder builderForValue) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.set(index, builderForValue.build());
          onChanged();
        } else {
          resultBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addResult(org.sas04225.proto.WifiScanResultProto.AccessPoint value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultIsMutable();
          result_.add(value);
          onChanged();
        } else {
          resultBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addResult(
          int index, org.sas04225.proto.WifiScanResultProto.AccessPoint value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultIsMutable();
          result_.add(index, value);
          onChanged();
        } else {
          resultBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addResult(
          org.sas04225.proto.WifiScanResultProto.AccessPoint.Builder builderForValue) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.add(builderForValue.build());
          onChanged();
        } else {
          resultBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addResult(
          int index, org.sas04225.proto.WifiScanResultProto.AccessPoint.Builder builderForValue) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.add(index, builderForValue.build());
          onChanged();
        } else {
          resultBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllResult(
          java.lang.Iterable<? extends org.sas04225.proto.WifiScanResultProto.AccessPoint> values) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          super.addAll(values, result_);
          onChanged();
        } else {
          resultBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearResult() {
        if (resultBuilder_ == null) {
          result_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          resultBuilder_.clear();
        }
        return this;
      }
      public Builder removeResult(int index) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.remove(index);
          onChanged();
        } else {
          resultBuilder_.remove(index);
        }
        return this;
      }
      public org.sas04225.proto.WifiScanResultProto.AccessPoint.Builder getResultBuilder(
          int index) {
        return getResultFieldBuilder().getBuilder(index);
      }
      public org.sas04225.proto.WifiScanResultProto.AccessPointOrBuilder getResultOrBuilder(
          int index) {
        if (resultBuilder_ == null) {
          return result_.get(index);  } else {
          return resultBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.sas04225.proto.WifiScanResultProto.AccessPointOrBuilder> 
           getResultOrBuilderList() {
        if (resultBuilder_ != null) {
          return resultBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(result_);
        }
      }
      public org.sas04225.proto.WifiScanResultProto.AccessPoint.Builder addResultBuilder() {
        return getResultFieldBuilder().addBuilder(
            org.sas04225.proto.WifiScanResultProto.AccessPoint.getDefaultInstance());
      }
      public org.sas04225.proto.WifiScanResultProto.AccessPoint.Builder addResultBuilder(
          int index) {
        return getResultFieldBuilder().addBuilder(
            index, org.sas04225.proto.WifiScanResultProto.AccessPoint.getDefaultInstance());
      }
      public java.util.List<org.sas04225.proto.WifiScanResultProto.AccessPoint.Builder> 
           getResultBuilderList() {
        return getResultFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.sas04225.proto.WifiScanResultProto.AccessPoint, org.sas04225.proto.WifiScanResultProto.AccessPoint.Builder, org.sas04225.proto.WifiScanResultProto.AccessPointOrBuilder> 
          getResultFieldBuilder() {
        if (resultBuilder_ == null) {
          resultBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.sas04225.proto.WifiScanResultProto.AccessPoint, org.sas04225.proto.WifiScanResultProto.AccessPoint.Builder, org.sas04225.proto.WifiScanResultProto.AccessPointOrBuilder>(
                  result_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          result_ = null;
        }
        return resultBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:org.sas04225.WifiScanResult)
    }
    
    static {
      defaultInstance = new WifiScanResult(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.sas04225.WifiScanResult)
  }
  
  public interface AccessPointOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string bssid = 1;
    boolean hasBssid();
    String getBssid();
    
    // required int32 level = 2;
    boolean hasLevel();
    int getLevel();
  }
  public static final class AccessPoint extends
      com.google.protobuf.GeneratedMessage
      implements AccessPointOrBuilder {
    // Use AccessPoint.newBuilder() to construct.
    private AccessPoint(Builder builder) {
      super(builder);
    }
    private AccessPoint(boolean noInit) {}
    
    private static final AccessPoint defaultInstance;
    public static AccessPoint getDefaultInstance() {
      return defaultInstance;
    }
    
    public AccessPoint getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sas04225.proto.WifiScanResultProto.internal_static_org_sas04225_AccessPoint_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sas04225.proto.WifiScanResultProto.internal_static_org_sas04225_AccessPoint_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string bssid = 1;
    public static final int BSSID_FIELD_NUMBER = 1;
    private java.lang.Object bssid_;
    public boolean hasBssid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getBssid() {
      java.lang.Object ref = bssid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          bssid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getBssidBytes() {
      java.lang.Object ref = bssid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        bssid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 level = 2;
    public static final int LEVEL_FIELD_NUMBER = 2;
    private int level_;
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getLevel() {
      return level_;
    }
    
    private void initFields() {
      bssid_ = "";
      level_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasBssid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getBssidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, level_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getBssidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, level_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.sas04225.proto.WifiScanResultProto.AccessPoint parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.sas04225.proto.WifiScanResultProto.AccessPoint parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.sas04225.proto.WifiScanResultProto.AccessPoint parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.sas04225.proto.WifiScanResultProto.AccessPoint parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.sas04225.proto.WifiScanResultProto.AccessPoint parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.sas04225.proto.WifiScanResultProto.AccessPoint parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.sas04225.proto.WifiScanResultProto.AccessPoint parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.sas04225.proto.WifiScanResultProto.AccessPoint parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.sas04225.proto.WifiScanResultProto.AccessPoint parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.sas04225.proto.WifiScanResultProto.AccessPoint parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.sas04225.proto.WifiScanResultProto.AccessPoint prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.sas04225.proto.WifiScanResultProto.AccessPointOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sas04225.proto.WifiScanResultProto.internal_static_org_sas04225_AccessPoint_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sas04225.proto.WifiScanResultProto.internal_static_org_sas04225_AccessPoint_fieldAccessorTable;
      }
      
      // Construct using org.sas04225.proto.WifiScanResultProto.AccessPoint.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        bssid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.sas04225.proto.WifiScanResultProto.AccessPoint.getDescriptor();
      }
      
      public org.sas04225.proto.WifiScanResultProto.AccessPoint getDefaultInstanceForType() {
        return org.sas04225.proto.WifiScanResultProto.AccessPoint.getDefaultInstance();
      }
      
      public org.sas04225.proto.WifiScanResultProto.AccessPoint build() {
        org.sas04225.proto.WifiScanResultProto.AccessPoint result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.sas04225.proto.WifiScanResultProto.AccessPoint buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.sas04225.proto.WifiScanResultProto.AccessPoint result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.sas04225.proto.WifiScanResultProto.AccessPoint buildPartial() {
        org.sas04225.proto.WifiScanResultProto.AccessPoint result = new org.sas04225.proto.WifiScanResultProto.AccessPoint(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.bssid_ = bssid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.level_ = level_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sas04225.proto.WifiScanResultProto.AccessPoint) {
          return mergeFrom((org.sas04225.proto.WifiScanResultProto.AccessPoint)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.sas04225.proto.WifiScanResultProto.AccessPoint other) {
        if (other == org.sas04225.proto.WifiScanResultProto.AccessPoint.getDefaultInstance()) return this;
        if (other.hasBssid()) {
          setBssid(other.getBssid());
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasBssid()) {
          
          return false;
        }
        if (!hasLevel()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              bssid_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              level_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string bssid = 1;
      private java.lang.Object bssid_ = "";
      public boolean hasBssid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getBssid() {
        java.lang.Object ref = bssid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          bssid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setBssid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        bssid_ = value;
        onChanged();
        return this;
      }
      public Builder clearBssid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bssid_ = getDefaultInstance().getBssid();
        onChanged();
        return this;
      }
      void setBssid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        bssid_ = value;
        onChanged();
      }
      
      // required int32 level = 2;
      private int level_ ;
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getLevel() {
        return level_;
      }
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000002;
        level_ = value;
        onChanged();
        return this;
      }
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        level_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.sas04225.AccessPoint)
    }
    
    static {
      defaultInstance = new AccessPoint(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.sas04225.AccessPoint)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_sas04225_WifiScanResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_sas04225_WifiScanResult_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_sas04225_AccessPoint_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_sas04225_AccessPoint_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024WifiScanResult.proto\022\014org.sas04225\"Q\n\016" +
      "WifiScanResult\022\024\n\014location_tag\030\001 \002(\t\022)\n\006" +
      "result\030\002 \003(\0132\031.org.sas04225.AccessPoint\"" +
      "+\n\013AccessPoint\022\r\n\005bssid\030\001 \002(\t\022\r\n\005level\030\002" +
      " \002(\005B)\n\022org.sas04225.protoB\023WifiScanResu" +
      "ltProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_sas04225_WifiScanResult_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_sas04225_WifiScanResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_sas04225_WifiScanResult_descriptor,
              new java.lang.String[] { "LocationTag", "Result", },
              org.sas04225.proto.WifiScanResultProto.WifiScanResult.class,
              org.sas04225.proto.WifiScanResultProto.WifiScanResult.Builder.class);
          internal_static_org_sas04225_AccessPoint_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_sas04225_AccessPoint_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_sas04225_AccessPoint_descriptor,
              new java.lang.String[] { "Bssid", "Level", },
              org.sas04225.proto.WifiScanResultProto.AccessPoint.class,
              org.sas04225.proto.WifiScanResultProto.AccessPoint.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
