// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ImageGroup.proto

package org.sas04225.proto;

public final class ImageGroupProto {
  private ImageGroupProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ImageGroupOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string group_name = 1;
    boolean hasGroupName();
    String getGroupName();
    
    // repeated string images = 2;
    java.util.List<String> getImagesList();
    int getImagesCount();
    String getImages(int index);
  }
  public static final class ImageGroup extends
      com.google.protobuf.GeneratedMessage
      implements ImageGroupOrBuilder {
    // Use ImageGroup.newBuilder() to construct.
    private ImageGroup(Builder builder) {
      super(builder);
    }
    private ImageGroup(boolean noInit) {}
    
    private static final ImageGroup defaultInstance;
    public static ImageGroup getDefaultInstance() {
      return defaultInstance;
    }
    
    public ImageGroup getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sas04225.proto.ImageGroupProto.internal_static_org_sas04225_proto_ImageGroup_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sas04225.proto.ImageGroupProto.internal_static_org_sas04225_proto_ImageGroup_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string group_name = 1;
    public static final int GROUP_NAME_FIELD_NUMBER = 1;
    private java.lang.Object groupName_;
    public boolean hasGroupName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getGroupName() {
      java.lang.Object ref = groupName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          groupName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getGroupNameBytes() {
      java.lang.Object ref = groupName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        groupName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated string images = 2;
    public static final int IMAGES_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList images_;
    public java.util.List<String>
        getImagesList() {
      return images_;
    }
    public int getImagesCount() {
      return images_.size();
    }
    public String getImages(int index) {
      return images_.get(index);
    }
    
    private void initFields() {
      groupName_ = "";
      images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasGroupName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getGroupNameBytes());
      }
      for (int i = 0; i < images_.size(); i++) {
        output.writeBytes(2, images_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getGroupNameBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < images_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(images_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getImagesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.sas04225.proto.ImageGroupProto.ImageGroup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.sas04225.proto.ImageGroupProto.ImageGroup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.sas04225.proto.ImageGroupProto.ImageGroup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.sas04225.proto.ImageGroupProto.ImageGroup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.sas04225.proto.ImageGroupProto.ImageGroup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.sas04225.proto.ImageGroupProto.ImageGroup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.sas04225.proto.ImageGroupProto.ImageGroup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.sas04225.proto.ImageGroupProto.ImageGroup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.sas04225.proto.ImageGroupProto.ImageGroup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.sas04225.proto.ImageGroupProto.ImageGroup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.sas04225.proto.ImageGroupProto.ImageGroup prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.sas04225.proto.ImageGroupProto.ImageGroupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sas04225.proto.ImageGroupProto.internal_static_org_sas04225_proto_ImageGroup_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sas04225.proto.ImageGroupProto.internal_static_org_sas04225_proto_ImageGroup_fieldAccessorTable;
      }
      
      // Construct using org.sas04225.proto.ImageGroupProto.ImageGroup.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        groupName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.sas04225.proto.ImageGroupProto.ImageGroup.getDescriptor();
      }
      
      public org.sas04225.proto.ImageGroupProto.ImageGroup getDefaultInstanceForType() {
        return org.sas04225.proto.ImageGroupProto.ImageGroup.getDefaultInstance();
      }
      
      public org.sas04225.proto.ImageGroupProto.ImageGroup build() {
        org.sas04225.proto.ImageGroupProto.ImageGroup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.sas04225.proto.ImageGroupProto.ImageGroup buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.sas04225.proto.ImageGroupProto.ImageGroup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.sas04225.proto.ImageGroupProto.ImageGroup buildPartial() {
        org.sas04225.proto.ImageGroupProto.ImageGroup result = new org.sas04225.proto.ImageGroupProto.ImageGroup(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.groupName_ = groupName_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          images_ = new com.google.protobuf.UnmodifiableLazyStringList(
              images_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.images_ = images_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sas04225.proto.ImageGroupProto.ImageGroup) {
          return mergeFrom((org.sas04225.proto.ImageGroupProto.ImageGroup)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.sas04225.proto.ImageGroupProto.ImageGroup other) {
        if (other == org.sas04225.proto.ImageGroupProto.ImageGroup.getDefaultInstance()) return this;
        if (other.hasGroupName()) {
          setGroupName(other.getGroupName());
        }
        if (!other.images_.isEmpty()) {
          if (images_.isEmpty()) {
            images_ = other.images_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureImagesIsMutable();
            images_.addAll(other.images_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasGroupName()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              groupName_ = input.readBytes();
              break;
            }
            case 18: {
              ensureImagesIsMutable();
              images_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string group_name = 1;
      private java.lang.Object groupName_ = "";
      public boolean hasGroupName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getGroupName() {
        java.lang.Object ref = groupName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          groupName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setGroupName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        groupName_ = value;
        onChanged();
        return this;
      }
      public Builder clearGroupName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        groupName_ = getDefaultInstance().getGroupName();
        onChanged();
        return this;
      }
      void setGroupName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        groupName_ = value;
        onChanged();
      }
      
      // repeated string images = 2;
      private com.google.protobuf.LazyStringList images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureImagesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          images_ = new com.google.protobuf.LazyStringArrayList(images_);
          bitField0_ |= 0x00000002;
         }
      }
      public java.util.List<String>
          getImagesList() {
        return java.util.Collections.unmodifiableList(images_);
      }
      public int getImagesCount() {
        return images_.size();
      }
      public String getImages(int index) {
        return images_.get(index);
      }
      public Builder setImages(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureImagesIsMutable();
        images_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addImages(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureImagesIsMutable();
        images_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllImages(
          java.lang.Iterable<String> values) {
        ensureImagesIsMutable();
        super.addAll(values, images_);
        onChanged();
        return this;
      }
      public Builder clearImages() {
        images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      void addImages(com.google.protobuf.ByteString value) {
        ensureImagesIsMutable();
        images_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:org.sas04225.proto.ImageGroup)
    }
    
    static {
      defaultInstance = new ImageGroup(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.sas04225.proto.ImageGroup)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_sas04225_proto_ImageGroup_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_sas04225_proto_ImageGroup_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020ImageGroup.proto\022\022org.sas04225.proto\"0" +
      "\n\nImageGroup\022\022\n\ngroup_name\030\001 \002(\t\022\016\n\006imag" +
      "es\030\002 \003(\tB%\n\022org.sas04225.protoB\017ImageGro" +
      "upProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_sas04225_proto_ImageGroup_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_sas04225_proto_ImageGroup_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_sas04225_proto_ImageGroup_descriptor,
              new java.lang.String[] { "GroupName", "Images", },
              org.sas04225.proto.ImageGroupProto.ImageGroup.class,
              org.sas04225.proto.ImageGroupProto.ImageGroup.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
