// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "DescriptorSetBuilderResult.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace org {
namespace sas04225 {
namespace proto {

namespace {

const ::google::protobuf::Descriptor* DescriptorSetBuilderResult_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DescriptorSetBuilderResult_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_DescriptorSetBuilderResult_2eproto() {
  protobuf_AddDesc_DescriptorSetBuilderResult_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "DescriptorSetBuilderResult.proto");
  GOOGLE_CHECK(file != NULL);
  DescriptorSetBuilderResult_descriptor_ = file->message_type(0);
  static const int DescriptorSetBuilderResult_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DescriptorSetBuilderResult, group_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DescriptorSetBuilderResult, descriptor_count_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DescriptorSetBuilderResult, startindex_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DescriptorSetBuilderResult, endindex_),
  };
  DescriptorSetBuilderResult_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DescriptorSetBuilderResult_descriptor_,
      DescriptorSetBuilderResult::default_instance_,
      DescriptorSetBuilderResult_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DescriptorSetBuilderResult, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DescriptorSetBuilderResult, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(DescriptorSetBuilderResult));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_DescriptorSetBuilderResult_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DescriptorSetBuilderResult_descriptor_, &DescriptorSetBuilderResult::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_DescriptorSetBuilderResult_2eproto() {
  delete DescriptorSetBuilderResult::default_instance_;
  delete DescriptorSetBuilderResult_reflection_;
}

void protobuf_AddDesc_DescriptorSetBuilderResult_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n DescriptorSetBuilderResult.proto\022\022org."
    "sas04225.proto\"p\n\032DescriptorSetBuilderRe"
    "sult\022\022\n\ngroup_name\030\001 \002(\t\022\030\n\020descriptor_c"
    "ount\030\002 \002(\r\022\022\n\nstartIndex\030\003 \002(\004\022\020\n\010endInd"
    "ex\030\004 \002(\004B5\n\022org.sas04225.protoB\037Descript"
    "orSetBuilderResultProto", 223);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "DescriptorSetBuilderResult.proto", &protobuf_RegisterTypes);
  DescriptorSetBuilderResult::default_instance_ = new DescriptorSetBuilderResult();
  DescriptorSetBuilderResult::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_DescriptorSetBuilderResult_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_DescriptorSetBuilderResult_2eproto {
  StaticDescriptorInitializer_DescriptorSetBuilderResult_2eproto() {
    protobuf_AddDesc_DescriptorSetBuilderResult_2eproto();
  }
} static_descriptor_initializer_DescriptorSetBuilderResult_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int DescriptorSetBuilderResult::kGroupNameFieldNumber;
const int DescriptorSetBuilderResult::kDescriptorCountFieldNumber;
const int DescriptorSetBuilderResult::kStartIndexFieldNumber;
const int DescriptorSetBuilderResult::kEndIndexFieldNumber;
#endif  // !_MSC_VER

DescriptorSetBuilderResult::DescriptorSetBuilderResult()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void DescriptorSetBuilderResult::InitAsDefaultInstance() {
}

DescriptorSetBuilderResult::DescriptorSetBuilderResult(const DescriptorSetBuilderResult& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void DescriptorSetBuilderResult::SharedCtor() {
  _cached_size_ = 0;
  group_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  descriptor_count_ = 0u;
  startindex_ = GOOGLE_ULONGLONG(0);
  endindex_ = GOOGLE_ULONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DescriptorSetBuilderResult::~DescriptorSetBuilderResult() {
  SharedDtor();
}

void DescriptorSetBuilderResult::SharedDtor() {
  if (group_name_ != &::google::protobuf::internal::kEmptyString) {
    delete group_name_;
  }
  if (this != default_instance_) {
  }
}

void DescriptorSetBuilderResult::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DescriptorSetBuilderResult::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DescriptorSetBuilderResult_descriptor_;
}

const DescriptorSetBuilderResult& DescriptorSetBuilderResult::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_DescriptorSetBuilderResult_2eproto();  return *default_instance_;
}

DescriptorSetBuilderResult* DescriptorSetBuilderResult::default_instance_ = NULL;

DescriptorSetBuilderResult* DescriptorSetBuilderResult::New() const {
  return new DescriptorSetBuilderResult;
}

void DescriptorSetBuilderResult::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_group_name()) {
      if (group_name_ != &::google::protobuf::internal::kEmptyString) {
        group_name_->clear();
      }
    }
    descriptor_count_ = 0u;
    startindex_ = GOOGLE_ULONGLONG(0);
    endindex_ = GOOGLE_ULONGLONG(0);
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool DescriptorSetBuilderResult::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string group_name = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_group_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->group_name().data(), this->group_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_descriptor_count;
        break;
      }
      
      // required uint32 descriptor_count = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_descriptor_count:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &descriptor_count_)));
          set_has_descriptor_count();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_startIndex;
        break;
      }
      
      // required uint64 startIndex = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_startIndex:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &startindex_)));
          set_has_startindex();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_endIndex;
        break;
      }
      
      // required uint64 endIndex = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_endIndex:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &endindex_)));
          set_has_endindex();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void DescriptorSetBuilderResult::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string group_name = 1;
  if (has_group_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->group_name().data(), this->group_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->group_name(), output);
  }
  
  // required uint32 descriptor_count = 2;
  if (has_descriptor_count()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->descriptor_count(), output);
  }
  
  // required uint64 startIndex = 3;
  if (has_startindex()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(3, this->startindex(), output);
  }
  
  // required uint64 endIndex = 4;
  if (has_endindex()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(4, this->endindex(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* DescriptorSetBuilderResult::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string group_name = 1;
  if (has_group_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->group_name().data(), this->group_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->group_name(), target);
  }
  
  // required uint32 descriptor_count = 2;
  if (has_descriptor_count()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->descriptor_count(), target);
  }
  
  // required uint64 startIndex = 3;
  if (has_startindex()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(3, this->startindex(), target);
  }
  
  // required uint64 endIndex = 4;
  if (has_endindex()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(4, this->endindex(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int DescriptorSetBuilderResult::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string group_name = 1;
    if (has_group_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->group_name());
    }
    
    // required uint32 descriptor_count = 2;
    if (has_descriptor_count()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->descriptor_count());
    }
    
    // required uint64 startIndex = 3;
    if (has_startindex()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->startindex());
    }
    
    // required uint64 endIndex = 4;
    if (has_endindex()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->endindex());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DescriptorSetBuilderResult::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const DescriptorSetBuilderResult* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const DescriptorSetBuilderResult*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void DescriptorSetBuilderResult::MergeFrom(const DescriptorSetBuilderResult& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_group_name()) {
      set_group_name(from.group_name());
    }
    if (from.has_descriptor_count()) {
      set_descriptor_count(from.descriptor_count());
    }
    if (from.has_startindex()) {
      set_startindex(from.startindex());
    }
    if (from.has_endindex()) {
      set_endindex(from.endindex());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void DescriptorSetBuilderResult::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DescriptorSetBuilderResult::CopyFrom(const DescriptorSetBuilderResult& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DescriptorSetBuilderResult::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;
  
  return true;
}

void DescriptorSetBuilderResult::Swap(DescriptorSetBuilderResult* other) {
  if (other != this) {
    std::swap(group_name_, other->group_name_);
    std::swap(descriptor_count_, other->descriptor_count_);
    std::swap(startindex_, other->startindex_);
    std::swap(endindex_, other->endindex_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata DescriptorSetBuilderResult::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DescriptorSetBuilderResult_descriptor_;
  metadata.reflection = DescriptorSetBuilderResult_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace sas04225
}  // namespace org

// @@protoc_insertion_point(global_scope)
