// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LookupResult.proto

package org.sas04225.proto;

public final class LookupResultProto {
  private LookupResultProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LookupResultOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint64 request_id = 1;
    boolean hasRequestId();
    long getRequestId();
    
    // repeated .org.sas04225.proto.DMatch matches = 2;
    java.util.List<org.sas04225.proto.LookupResultProto.DMatch> 
        getMatchesList();
    org.sas04225.proto.LookupResultProto.DMatch getMatches(int index);
    int getMatchesCount();
    java.util.List<? extends org.sas04225.proto.LookupResultProto.DMatchOrBuilder> 
        getMatchesOrBuilderList();
    org.sas04225.proto.LookupResultProto.DMatchOrBuilder getMatchesOrBuilder(
        int index);
  }
  public static final class LookupResult extends
      com.google.protobuf.GeneratedMessage
      implements LookupResultOrBuilder {
    // Use LookupResult.newBuilder() to construct.
    private LookupResult(Builder builder) {
      super(builder);
    }
    private LookupResult(boolean noInit) {}
    
    private static final LookupResult defaultInstance;
    public static LookupResult getDefaultInstance() {
      return defaultInstance;
    }
    
    public LookupResult getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sas04225.proto.LookupResultProto.internal_static_org_sas04225_proto_LookupResult_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sas04225.proto.LookupResultProto.internal_static_org_sas04225_proto_LookupResult_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint64 request_id = 1;
    public static final int REQUEST_ID_FIELD_NUMBER = 1;
    private long requestId_;
    public boolean hasRequestId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getRequestId() {
      return requestId_;
    }
    
    // repeated .org.sas04225.proto.DMatch matches = 2;
    public static final int MATCHES_FIELD_NUMBER = 2;
    private java.util.List<org.sas04225.proto.LookupResultProto.DMatch> matches_;
    public java.util.List<org.sas04225.proto.LookupResultProto.DMatch> getMatchesList() {
      return matches_;
    }
    public java.util.List<? extends org.sas04225.proto.LookupResultProto.DMatchOrBuilder> 
        getMatchesOrBuilderList() {
      return matches_;
    }
    public int getMatchesCount() {
      return matches_.size();
    }
    public org.sas04225.proto.LookupResultProto.DMatch getMatches(int index) {
      return matches_.get(index);
    }
    public org.sas04225.proto.LookupResultProto.DMatchOrBuilder getMatchesOrBuilder(
        int index) {
      return matches_.get(index);
    }
    
    private void initFields() {
      requestId_ = 0L;
      matches_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRequestId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getMatchesCount(); i++) {
        if (!getMatches(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, requestId_);
      }
      for (int i = 0; i < matches_.size(); i++) {
        output.writeMessage(2, matches_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, requestId_);
      }
      for (int i = 0; i < matches_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, matches_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.sas04225.proto.LookupResultProto.LookupResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.sas04225.proto.LookupResultProto.LookupResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.sas04225.proto.LookupResultProto.LookupResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.sas04225.proto.LookupResultProto.LookupResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.sas04225.proto.LookupResultProto.LookupResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.sas04225.proto.LookupResultProto.LookupResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.sas04225.proto.LookupResultProto.LookupResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.sas04225.proto.LookupResultProto.LookupResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.sas04225.proto.LookupResultProto.LookupResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.sas04225.proto.LookupResultProto.LookupResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.sas04225.proto.LookupResultProto.LookupResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.sas04225.proto.LookupResultProto.LookupResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sas04225.proto.LookupResultProto.internal_static_org_sas04225_proto_LookupResult_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sas04225.proto.LookupResultProto.internal_static_org_sas04225_proto_LookupResult_fieldAccessorTable;
      }
      
      // Construct using org.sas04225.proto.LookupResultProto.LookupResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMatchesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        requestId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (matchesBuilder_ == null) {
          matches_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          matchesBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.sas04225.proto.LookupResultProto.LookupResult.getDescriptor();
      }
      
      public org.sas04225.proto.LookupResultProto.LookupResult getDefaultInstanceForType() {
        return org.sas04225.proto.LookupResultProto.LookupResult.getDefaultInstance();
      }
      
      public org.sas04225.proto.LookupResultProto.LookupResult build() {
        org.sas04225.proto.LookupResultProto.LookupResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.sas04225.proto.LookupResultProto.LookupResult buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.sas04225.proto.LookupResultProto.LookupResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.sas04225.proto.LookupResultProto.LookupResult buildPartial() {
        org.sas04225.proto.LookupResultProto.LookupResult result = new org.sas04225.proto.LookupResultProto.LookupResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.requestId_ = requestId_;
        if (matchesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            matches_ = java.util.Collections.unmodifiableList(matches_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.matches_ = matches_;
        } else {
          result.matches_ = matchesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sas04225.proto.LookupResultProto.LookupResult) {
          return mergeFrom((org.sas04225.proto.LookupResultProto.LookupResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.sas04225.proto.LookupResultProto.LookupResult other) {
        if (other == org.sas04225.proto.LookupResultProto.LookupResult.getDefaultInstance()) return this;
        if (other.hasRequestId()) {
          setRequestId(other.getRequestId());
        }
        if (matchesBuilder_ == null) {
          if (!other.matches_.isEmpty()) {
            if (matches_.isEmpty()) {
              matches_ = other.matches_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureMatchesIsMutable();
              matches_.addAll(other.matches_);
            }
            onChanged();
          }
        } else {
          if (!other.matches_.isEmpty()) {
            if (matchesBuilder_.isEmpty()) {
              matchesBuilder_.dispose();
              matchesBuilder_ = null;
              matches_ = other.matches_;
              bitField0_ = (bitField0_ & ~0x00000002);
              matchesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMatchesFieldBuilder() : null;
            } else {
              matchesBuilder_.addAllMessages(other.matches_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasRequestId()) {
          
          return false;
        }
        for (int i = 0; i < getMatchesCount(); i++) {
          if (!getMatches(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              requestId_ = input.readUInt64();
              break;
            }
            case 18: {
              org.sas04225.proto.LookupResultProto.DMatch.Builder subBuilder = org.sas04225.proto.LookupResultProto.DMatch.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMatches(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint64 request_id = 1;
      private long requestId_ ;
      public boolean hasRequestId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getRequestId() {
        return requestId_;
      }
      public Builder setRequestId(long value) {
        bitField0_ |= 0x00000001;
        requestId_ = value;
        onChanged();
        return this;
      }
      public Builder clearRequestId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestId_ = 0L;
        onChanged();
        return this;
      }
      
      // repeated .org.sas04225.proto.DMatch matches = 2;
      private java.util.List<org.sas04225.proto.LookupResultProto.DMatch> matches_ =
        java.util.Collections.emptyList();
      private void ensureMatchesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          matches_ = new java.util.ArrayList<org.sas04225.proto.LookupResultProto.DMatch>(matches_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.sas04225.proto.LookupResultProto.DMatch, org.sas04225.proto.LookupResultProto.DMatch.Builder, org.sas04225.proto.LookupResultProto.DMatchOrBuilder> matchesBuilder_;
      
      public java.util.List<org.sas04225.proto.LookupResultProto.DMatch> getMatchesList() {
        if (matchesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(matches_);
        } else {
          return matchesBuilder_.getMessageList();
        }
      }
      public int getMatchesCount() {
        if (matchesBuilder_ == null) {
          return matches_.size();
        } else {
          return matchesBuilder_.getCount();
        }
      }
      public org.sas04225.proto.LookupResultProto.DMatch getMatches(int index) {
        if (matchesBuilder_ == null) {
          return matches_.get(index);
        } else {
          return matchesBuilder_.getMessage(index);
        }
      }
      public Builder setMatches(
          int index, org.sas04225.proto.LookupResultProto.DMatch value) {
        if (matchesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMatchesIsMutable();
          matches_.set(index, value);
          onChanged();
        } else {
          matchesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setMatches(
          int index, org.sas04225.proto.LookupResultProto.DMatch.Builder builderForValue) {
        if (matchesBuilder_ == null) {
          ensureMatchesIsMutable();
          matches_.set(index, builderForValue.build());
          onChanged();
        } else {
          matchesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addMatches(org.sas04225.proto.LookupResultProto.DMatch value) {
        if (matchesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMatchesIsMutable();
          matches_.add(value);
          onChanged();
        } else {
          matchesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addMatches(
          int index, org.sas04225.proto.LookupResultProto.DMatch value) {
        if (matchesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMatchesIsMutable();
          matches_.add(index, value);
          onChanged();
        } else {
          matchesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addMatches(
          org.sas04225.proto.LookupResultProto.DMatch.Builder builderForValue) {
        if (matchesBuilder_ == null) {
          ensureMatchesIsMutable();
          matches_.add(builderForValue.build());
          onChanged();
        } else {
          matchesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addMatches(
          int index, org.sas04225.proto.LookupResultProto.DMatch.Builder builderForValue) {
        if (matchesBuilder_ == null) {
          ensureMatchesIsMutable();
          matches_.add(index, builderForValue.build());
          onChanged();
        } else {
          matchesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllMatches(
          java.lang.Iterable<? extends org.sas04225.proto.LookupResultProto.DMatch> values) {
        if (matchesBuilder_ == null) {
          ensureMatchesIsMutable();
          super.addAll(values, matches_);
          onChanged();
        } else {
          matchesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearMatches() {
        if (matchesBuilder_ == null) {
          matches_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          matchesBuilder_.clear();
        }
        return this;
      }
      public Builder removeMatches(int index) {
        if (matchesBuilder_ == null) {
          ensureMatchesIsMutable();
          matches_.remove(index);
          onChanged();
        } else {
          matchesBuilder_.remove(index);
        }
        return this;
      }
      public org.sas04225.proto.LookupResultProto.DMatch.Builder getMatchesBuilder(
          int index) {
        return getMatchesFieldBuilder().getBuilder(index);
      }
      public org.sas04225.proto.LookupResultProto.DMatchOrBuilder getMatchesOrBuilder(
          int index) {
        if (matchesBuilder_ == null) {
          return matches_.get(index);  } else {
          return matchesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.sas04225.proto.LookupResultProto.DMatchOrBuilder> 
           getMatchesOrBuilderList() {
        if (matchesBuilder_ != null) {
          return matchesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(matches_);
        }
      }
      public org.sas04225.proto.LookupResultProto.DMatch.Builder addMatchesBuilder() {
        return getMatchesFieldBuilder().addBuilder(
            org.sas04225.proto.LookupResultProto.DMatch.getDefaultInstance());
      }
      public org.sas04225.proto.LookupResultProto.DMatch.Builder addMatchesBuilder(
          int index) {
        return getMatchesFieldBuilder().addBuilder(
            index, org.sas04225.proto.LookupResultProto.DMatch.getDefaultInstance());
      }
      public java.util.List<org.sas04225.proto.LookupResultProto.DMatch.Builder> 
           getMatchesBuilderList() {
        return getMatchesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.sas04225.proto.LookupResultProto.DMatch, org.sas04225.proto.LookupResultProto.DMatch.Builder, org.sas04225.proto.LookupResultProto.DMatchOrBuilder> 
          getMatchesFieldBuilder() {
        if (matchesBuilder_ == null) {
          matchesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.sas04225.proto.LookupResultProto.DMatch, org.sas04225.proto.LookupResultProto.DMatch.Builder, org.sas04225.proto.LookupResultProto.DMatchOrBuilder>(
                  matches_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          matches_ = null;
        }
        return matchesBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:org.sas04225.proto.LookupResult)
    }
    
    static {
      defaultInstance = new LookupResult(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.sas04225.proto.LookupResult)
  }
  
  public interface DMatchOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint32 distance = 1;
    boolean hasDistance();
    int getDistance();
    
    // required uint64 trainIdx = 2;
    boolean hasTrainIdx();
    long getTrainIdx();
  }
  public static final class DMatch extends
      com.google.protobuf.GeneratedMessage
      implements DMatchOrBuilder {
    // Use DMatch.newBuilder() to construct.
    private DMatch(Builder builder) {
      super(builder);
    }
    private DMatch(boolean noInit) {}
    
    private static final DMatch defaultInstance;
    public static DMatch getDefaultInstance() {
      return defaultInstance;
    }
    
    public DMatch getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sas04225.proto.LookupResultProto.internal_static_org_sas04225_proto_DMatch_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sas04225.proto.LookupResultProto.internal_static_org_sas04225_proto_DMatch_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint32 distance = 1;
    public static final int DISTANCE_FIELD_NUMBER = 1;
    private int distance_;
    public boolean hasDistance() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getDistance() {
      return distance_;
    }
    
    // required uint64 trainIdx = 2;
    public static final int TRAINIDX_FIELD_NUMBER = 2;
    private long trainIdx_;
    public boolean hasTrainIdx() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getTrainIdx() {
      return trainIdx_;
    }
    
    private void initFields() {
      distance_ = 0;
      trainIdx_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasDistance()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTrainIdx()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, distance_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, trainIdx_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, distance_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, trainIdx_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.sas04225.proto.LookupResultProto.DMatch parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.sas04225.proto.LookupResultProto.DMatch parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.sas04225.proto.LookupResultProto.DMatch parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.sas04225.proto.LookupResultProto.DMatch parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.sas04225.proto.LookupResultProto.DMatch parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.sas04225.proto.LookupResultProto.DMatch parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.sas04225.proto.LookupResultProto.DMatch parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.sas04225.proto.LookupResultProto.DMatch parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.sas04225.proto.LookupResultProto.DMatch parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.sas04225.proto.LookupResultProto.DMatch parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.sas04225.proto.LookupResultProto.DMatch prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.sas04225.proto.LookupResultProto.DMatchOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sas04225.proto.LookupResultProto.internal_static_org_sas04225_proto_DMatch_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sas04225.proto.LookupResultProto.internal_static_org_sas04225_proto_DMatch_fieldAccessorTable;
      }
      
      // Construct using org.sas04225.proto.LookupResultProto.DMatch.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        distance_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        trainIdx_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.sas04225.proto.LookupResultProto.DMatch.getDescriptor();
      }
      
      public org.sas04225.proto.LookupResultProto.DMatch getDefaultInstanceForType() {
        return org.sas04225.proto.LookupResultProto.DMatch.getDefaultInstance();
      }
      
      public org.sas04225.proto.LookupResultProto.DMatch build() {
        org.sas04225.proto.LookupResultProto.DMatch result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.sas04225.proto.LookupResultProto.DMatch buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.sas04225.proto.LookupResultProto.DMatch result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.sas04225.proto.LookupResultProto.DMatch buildPartial() {
        org.sas04225.proto.LookupResultProto.DMatch result = new org.sas04225.proto.LookupResultProto.DMatch(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.distance_ = distance_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.trainIdx_ = trainIdx_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sas04225.proto.LookupResultProto.DMatch) {
          return mergeFrom((org.sas04225.proto.LookupResultProto.DMatch)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.sas04225.proto.LookupResultProto.DMatch other) {
        if (other == org.sas04225.proto.LookupResultProto.DMatch.getDefaultInstance()) return this;
        if (other.hasDistance()) {
          setDistance(other.getDistance());
        }
        if (other.hasTrainIdx()) {
          setTrainIdx(other.getTrainIdx());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasDistance()) {
          
          return false;
        }
        if (!hasTrainIdx()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              distance_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              trainIdx_ = input.readUInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint32 distance = 1;
      private int distance_ ;
      public boolean hasDistance() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getDistance() {
        return distance_;
      }
      public Builder setDistance(int value) {
        bitField0_ |= 0x00000001;
        distance_ = value;
        onChanged();
        return this;
      }
      public Builder clearDistance() {
        bitField0_ = (bitField0_ & ~0x00000001);
        distance_ = 0;
        onChanged();
        return this;
      }
      
      // required uint64 trainIdx = 2;
      private long trainIdx_ ;
      public boolean hasTrainIdx() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getTrainIdx() {
        return trainIdx_;
      }
      public Builder setTrainIdx(long value) {
        bitField0_ |= 0x00000002;
        trainIdx_ = value;
        onChanged();
        return this;
      }
      public Builder clearTrainIdx() {
        bitField0_ = (bitField0_ & ~0x00000002);
        trainIdx_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.sas04225.proto.DMatch)
    }
    
    static {
      defaultInstance = new DMatch(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.sas04225.proto.DMatch)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_sas04225_proto_LookupResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_sas04225_proto_LookupResult_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_sas04225_proto_DMatch_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_sas04225_proto_DMatch_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022LookupResult.proto\022\022org.sas04225.proto" +
      "\"O\n\014LookupResult\022\022\n\nrequest_id\030\001 \002(\004\022+\n\007" +
      "matches\030\002 \003(\0132\032.org.sas04225.proto.DMatc" +
      "h\",\n\006DMatch\022\020\n\010distance\030\001 \002(\r\022\020\n\010trainId" +
      "x\030\002 \002(\004B\'\n\022org.sas04225.protoB\021LookupRes" +
      "ultProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_sas04225_proto_LookupResult_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_sas04225_proto_LookupResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_sas04225_proto_LookupResult_descriptor,
              new java.lang.String[] { "RequestId", "Matches", },
              org.sas04225.proto.LookupResultProto.LookupResult.class,
              org.sas04225.proto.LookupResultProto.LookupResult.Builder.class);
          internal_static_org_sas04225_proto_DMatch_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_sas04225_proto_DMatch_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_sas04225_proto_DMatch_descriptor,
              new java.lang.String[] { "Distance", "TrainIdx", },
              org.sas04225.proto.LookupResultProto.DMatch.class,
              org.sas04225.proto.LookupResultProto.DMatch.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
