// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecognitionServerBackendInit.proto

package org.sas04225.proto;

public final class RecognitionServerBackendInitProto {
  private RecognitionServerBackendInitProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RecognitionServerBackendInitOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint64 descriptor_count = 1;
    boolean hasDescriptorCount();
    long getDescriptorCount();
    
    // required string cache_path = 2;
    boolean hasCachePath();
    String getCachePath();
  }
  public static final class RecognitionServerBackendInit extends
      com.google.protobuf.GeneratedMessage
      implements RecognitionServerBackendInitOrBuilder {
    // Use RecognitionServerBackendInit.newBuilder() to construct.
    private RecognitionServerBackendInit(Builder builder) {
      super(builder);
    }
    private RecognitionServerBackendInit(boolean noInit) {}
    
    private static final RecognitionServerBackendInit defaultInstance;
    public static RecognitionServerBackendInit getDefaultInstance() {
      return defaultInstance;
    }
    
    public RecognitionServerBackendInit getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sas04225.proto.RecognitionServerBackendInitProto.internal_static_org_sas04225_proto_RecognitionServerBackendInit_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sas04225.proto.RecognitionServerBackendInitProto.internal_static_org_sas04225_proto_RecognitionServerBackendInit_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint64 descriptor_count = 1;
    public static final int DESCRIPTOR_COUNT_FIELD_NUMBER = 1;
    private long descriptorCount_;
    public boolean hasDescriptorCount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getDescriptorCount() {
      return descriptorCount_;
    }
    
    // required string cache_path = 2;
    public static final int CACHE_PATH_FIELD_NUMBER = 2;
    private java.lang.Object cachePath_;
    public boolean hasCachePath() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getCachePath() {
      java.lang.Object ref = cachePath_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          cachePath_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCachePathBytes() {
      java.lang.Object ref = cachePath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        cachePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      descriptorCount_ = 0L;
      cachePath_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasDescriptorCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCachePath()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, descriptorCount_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCachePathBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, descriptorCount_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCachePathBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.sas04225.proto.RecognitionServerBackendInitProto.RecognitionServerBackendInit parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.sas04225.proto.RecognitionServerBackendInitProto.RecognitionServerBackendInit parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.sas04225.proto.RecognitionServerBackendInitProto.RecognitionServerBackendInit parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.sas04225.proto.RecognitionServerBackendInitProto.RecognitionServerBackendInit parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.sas04225.proto.RecognitionServerBackendInitProto.RecognitionServerBackendInit parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.sas04225.proto.RecognitionServerBackendInitProto.RecognitionServerBackendInit parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.sas04225.proto.RecognitionServerBackendInitProto.RecognitionServerBackendInit parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.sas04225.proto.RecognitionServerBackendInitProto.RecognitionServerBackendInit parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.sas04225.proto.RecognitionServerBackendInitProto.RecognitionServerBackendInit parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.sas04225.proto.RecognitionServerBackendInitProto.RecognitionServerBackendInit parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.sas04225.proto.RecognitionServerBackendInitProto.RecognitionServerBackendInit prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.sas04225.proto.RecognitionServerBackendInitProto.RecognitionServerBackendInitOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sas04225.proto.RecognitionServerBackendInitProto.internal_static_org_sas04225_proto_RecognitionServerBackendInit_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sas04225.proto.RecognitionServerBackendInitProto.internal_static_org_sas04225_proto_RecognitionServerBackendInit_fieldAccessorTable;
      }
      
      // Construct using org.sas04225.proto.RecognitionServerBackendInitProto.RecognitionServerBackendInit.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        descriptorCount_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        cachePath_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.sas04225.proto.RecognitionServerBackendInitProto.RecognitionServerBackendInit.getDescriptor();
      }
      
      public org.sas04225.proto.RecognitionServerBackendInitProto.RecognitionServerBackendInit getDefaultInstanceForType() {
        return org.sas04225.proto.RecognitionServerBackendInitProto.RecognitionServerBackendInit.getDefaultInstance();
      }
      
      public org.sas04225.proto.RecognitionServerBackendInitProto.RecognitionServerBackendInit build() {
        org.sas04225.proto.RecognitionServerBackendInitProto.RecognitionServerBackendInit result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.sas04225.proto.RecognitionServerBackendInitProto.RecognitionServerBackendInit buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.sas04225.proto.RecognitionServerBackendInitProto.RecognitionServerBackendInit result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.sas04225.proto.RecognitionServerBackendInitProto.RecognitionServerBackendInit buildPartial() {
        org.sas04225.proto.RecognitionServerBackendInitProto.RecognitionServerBackendInit result = new org.sas04225.proto.RecognitionServerBackendInitProto.RecognitionServerBackendInit(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.descriptorCount_ = descriptorCount_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cachePath_ = cachePath_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sas04225.proto.RecognitionServerBackendInitProto.RecognitionServerBackendInit) {
          return mergeFrom((org.sas04225.proto.RecognitionServerBackendInitProto.RecognitionServerBackendInit)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.sas04225.proto.RecognitionServerBackendInitProto.RecognitionServerBackendInit other) {
        if (other == org.sas04225.proto.RecognitionServerBackendInitProto.RecognitionServerBackendInit.getDefaultInstance()) return this;
        if (other.hasDescriptorCount()) {
          setDescriptorCount(other.getDescriptorCount());
        }
        if (other.hasCachePath()) {
          setCachePath(other.getCachePath());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasDescriptorCount()) {
          
          return false;
        }
        if (!hasCachePath()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              descriptorCount_ = input.readUInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              cachePath_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint64 descriptor_count = 1;
      private long descriptorCount_ ;
      public boolean hasDescriptorCount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getDescriptorCount() {
        return descriptorCount_;
      }
      public Builder setDescriptorCount(long value) {
        bitField0_ |= 0x00000001;
        descriptorCount_ = value;
        onChanged();
        return this;
      }
      public Builder clearDescriptorCount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        descriptorCount_ = 0L;
        onChanged();
        return this;
      }
      
      // required string cache_path = 2;
      private java.lang.Object cachePath_ = "";
      public boolean hasCachePath() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getCachePath() {
        java.lang.Object ref = cachePath_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          cachePath_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCachePath(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        cachePath_ = value;
        onChanged();
        return this;
      }
      public Builder clearCachePath() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cachePath_ = getDefaultInstance().getCachePath();
        onChanged();
        return this;
      }
      void setCachePath(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        cachePath_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:org.sas04225.proto.RecognitionServerBackendInit)
    }
    
    static {
      defaultInstance = new RecognitionServerBackendInit(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.sas04225.proto.RecognitionServerBackendInit)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_sas04225_proto_RecognitionServerBackendInit_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_sas04225_proto_RecognitionServerBackendInit_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"RecognitionServerBackendInit.proto\022\022or" +
      "g.sas04225.proto\"L\n\034RecognitionServerBac" +
      "kendInit\022\030\n\020descriptor_count\030\001 \002(\004\022\022\n\nca" +
      "che_path\030\002 \002(\tB7\n\022org.sas04225.protoB!Re" +
      "cognitionServerBackendInitProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_sas04225_proto_RecognitionServerBackendInit_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_sas04225_proto_RecognitionServerBackendInit_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_sas04225_proto_RecognitionServerBackendInit_descriptor,
              new java.lang.String[] { "DescriptorCount", "CachePath", },
              org.sas04225.proto.RecognitionServerBackendInitProto.RecognitionServerBackendInit.class,
              org.sas04225.proto.RecognitionServerBackendInitProto.RecognitionServerBackendInit.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
