// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecognitionServerQuery.proto

package org.sas04225.proto;

public final class RecognitionServerQueryProto {
  private RecognitionServerQueryProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum QueryType
      implements com.google.protobuf.ProtocolMessageEnum {
    LOCATION_BASED_QUERY(0, 0),
    GENERAL_QUERY(1, 1),
    ;
    
    public static final int LOCATION_BASED_QUERY_VALUE = 0;
    public static final int GENERAL_QUERY_VALUE = 1;
    
    
    public final int getNumber() { return value; }
    
    public static QueryType valueOf(int value) {
      switch (value) {
        case 0: return LOCATION_BASED_QUERY;
        case 1: return GENERAL_QUERY;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<QueryType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<QueryType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<QueryType>() {
            public QueryType findValueByNumber(int number) {
              return QueryType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.sas04225.proto.RecognitionServerQueryProto.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final QueryType[] VALUES = {
      LOCATION_BASED_QUERY, GENERAL_QUERY, 
    };
    
    public static QueryType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private QueryType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:org.sas04225.proto.QueryType)
  }
  
  public enum QueryDataType
      implements com.google.protobuf.ProtocolMessageEnum {
    JPEG_IMAGE(0, 0),
    FREAK_DESCRIPTOR(1, 1),
    ;
    
    public static final int JPEG_IMAGE_VALUE = 0;
    public static final int FREAK_DESCRIPTOR_VALUE = 1;
    
    
    public final int getNumber() { return value; }
    
    public static QueryDataType valueOf(int value) {
      switch (value) {
        case 0: return JPEG_IMAGE;
        case 1: return FREAK_DESCRIPTOR;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<QueryDataType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<QueryDataType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<QueryDataType>() {
            public QueryDataType findValueByNumber(int number) {
              return QueryDataType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.sas04225.proto.RecognitionServerQueryProto.getDescriptor().getEnumTypes().get(1);
    }
    
    private static final QueryDataType[] VALUES = {
      JPEG_IMAGE, FREAK_DESCRIPTOR, 
    };
    
    public static QueryDataType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private QueryDataType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:org.sas04225.proto.QueryDataType)
  }
  
  public interface QueryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint64 request_id = 1;
    boolean hasRequestId();
    long getRequestId();
    
    // required .org.sas04225.proto.QueryType queryType = 2;
    boolean hasQueryType();
    org.sas04225.proto.RecognitionServerQueryProto.QueryType getQueryType();
    
    // required .org.sas04225.proto.QueryDataType queryDataType = 3;
    boolean hasQueryDataType();
    org.sas04225.proto.RecognitionServerQueryProto.QueryDataType getQueryDataType();
    
    // required uint32 location_id = 4;
    boolean hasLocationId();
    int getLocationId();
    
    // required bytes queryData = 5;
    boolean hasQueryData();
    com.google.protobuf.ByteString getQueryData();
  }
  public static final class Query extends
      com.google.protobuf.GeneratedMessage
      implements QueryOrBuilder {
    // Use Query.newBuilder() to construct.
    private Query(Builder builder) {
      super(builder);
    }
    private Query(boolean noInit) {}
    
    private static final Query defaultInstance;
    public static Query getDefaultInstance() {
      return defaultInstance;
    }
    
    public Query getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sas04225.proto.RecognitionServerQueryProto.internal_static_org_sas04225_proto_Query_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sas04225.proto.RecognitionServerQueryProto.internal_static_org_sas04225_proto_Query_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint64 request_id = 1;
    public static final int REQUEST_ID_FIELD_NUMBER = 1;
    private long requestId_;
    public boolean hasRequestId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getRequestId() {
      return requestId_;
    }
    
    // required .org.sas04225.proto.QueryType queryType = 2;
    public static final int QUERYTYPE_FIELD_NUMBER = 2;
    private org.sas04225.proto.RecognitionServerQueryProto.QueryType queryType_;
    public boolean hasQueryType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public org.sas04225.proto.RecognitionServerQueryProto.QueryType getQueryType() {
      return queryType_;
    }
    
    // required .org.sas04225.proto.QueryDataType queryDataType = 3;
    public static final int QUERYDATATYPE_FIELD_NUMBER = 3;
    private org.sas04225.proto.RecognitionServerQueryProto.QueryDataType queryDataType_;
    public boolean hasQueryDataType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public org.sas04225.proto.RecognitionServerQueryProto.QueryDataType getQueryDataType() {
      return queryDataType_;
    }
    
    // required uint32 location_id = 4;
    public static final int LOCATION_ID_FIELD_NUMBER = 4;
    private int locationId_;
    public boolean hasLocationId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getLocationId() {
      return locationId_;
    }
    
    // required bytes queryData = 5;
    public static final int QUERYDATA_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString queryData_;
    public boolean hasQueryData() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public com.google.protobuf.ByteString getQueryData() {
      return queryData_;
    }
    
    private void initFields() {
      requestId_ = 0L;
      queryType_ = org.sas04225.proto.RecognitionServerQueryProto.QueryType.LOCATION_BASED_QUERY;
      queryDataType_ = org.sas04225.proto.RecognitionServerQueryProto.QueryDataType.JPEG_IMAGE;
      locationId_ = 0;
      queryData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRequestId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQueryType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQueryDataType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLocationId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQueryData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, requestId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, queryType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, queryDataType_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, locationId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, queryData_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, requestId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, queryType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, queryDataType_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, locationId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, queryData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.sas04225.proto.RecognitionServerQueryProto.Query parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.sas04225.proto.RecognitionServerQueryProto.Query parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.sas04225.proto.RecognitionServerQueryProto.Query parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.sas04225.proto.RecognitionServerQueryProto.Query parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.sas04225.proto.RecognitionServerQueryProto.Query parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.sas04225.proto.RecognitionServerQueryProto.Query parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.sas04225.proto.RecognitionServerQueryProto.Query parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.sas04225.proto.RecognitionServerQueryProto.Query parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.sas04225.proto.RecognitionServerQueryProto.Query parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.sas04225.proto.RecognitionServerQueryProto.Query parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.sas04225.proto.RecognitionServerQueryProto.Query prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.sas04225.proto.RecognitionServerQueryProto.QueryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sas04225.proto.RecognitionServerQueryProto.internal_static_org_sas04225_proto_Query_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sas04225.proto.RecognitionServerQueryProto.internal_static_org_sas04225_proto_Query_fieldAccessorTable;
      }
      
      // Construct using org.sas04225.proto.RecognitionServerQueryProto.Query.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        requestId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        queryType_ = org.sas04225.proto.RecognitionServerQueryProto.QueryType.LOCATION_BASED_QUERY;
        bitField0_ = (bitField0_ & ~0x00000002);
        queryDataType_ = org.sas04225.proto.RecognitionServerQueryProto.QueryDataType.JPEG_IMAGE;
        bitField0_ = (bitField0_ & ~0x00000004);
        locationId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        queryData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.sas04225.proto.RecognitionServerQueryProto.Query.getDescriptor();
      }
      
      public org.sas04225.proto.RecognitionServerQueryProto.Query getDefaultInstanceForType() {
        return org.sas04225.proto.RecognitionServerQueryProto.Query.getDefaultInstance();
      }
      
      public org.sas04225.proto.RecognitionServerQueryProto.Query build() {
        org.sas04225.proto.RecognitionServerQueryProto.Query result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.sas04225.proto.RecognitionServerQueryProto.Query buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.sas04225.proto.RecognitionServerQueryProto.Query result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.sas04225.proto.RecognitionServerQueryProto.Query buildPartial() {
        org.sas04225.proto.RecognitionServerQueryProto.Query result = new org.sas04225.proto.RecognitionServerQueryProto.Query(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.requestId_ = requestId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.queryType_ = queryType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.queryDataType_ = queryDataType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.locationId_ = locationId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.queryData_ = queryData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sas04225.proto.RecognitionServerQueryProto.Query) {
          return mergeFrom((org.sas04225.proto.RecognitionServerQueryProto.Query)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.sas04225.proto.RecognitionServerQueryProto.Query other) {
        if (other == org.sas04225.proto.RecognitionServerQueryProto.Query.getDefaultInstance()) return this;
        if (other.hasRequestId()) {
          setRequestId(other.getRequestId());
        }
        if (other.hasQueryType()) {
          setQueryType(other.getQueryType());
        }
        if (other.hasQueryDataType()) {
          setQueryDataType(other.getQueryDataType());
        }
        if (other.hasLocationId()) {
          setLocationId(other.getLocationId());
        }
        if (other.hasQueryData()) {
          setQueryData(other.getQueryData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasRequestId()) {
          
          return false;
        }
        if (!hasQueryType()) {
          
          return false;
        }
        if (!hasQueryDataType()) {
          
          return false;
        }
        if (!hasLocationId()) {
          
          return false;
        }
        if (!hasQueryData()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              requestId_ = input.readUInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              org.sas04225.proto.RecognitionServerQueryProto.QueryType value = org.sas04225.proto.RecognitionServerQueryProto.QueryType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                queryType_ = value;
              }
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              org.sas04225.proto.RecognitionServerQueryProto.QueryDataType value = org.sas04225.proto.RecognitionServerQueryProto.QueryDataType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                queryDataType_ = value;
              }
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              locationId_ = input.readUInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              queryData_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint64 request_id = 1;
      private long requestId_ ;
      public boolean hasRequestId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getRequestId() {
        return requestId_;
      }
      public Builder setRequestId(long value) {
        bitField0_ |= 0x00000001;
        requestId_ = value;
        onChanged();
        return this;
      }
      public Builder clearRequestId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestId_ = 0L;
        onChanged();
        return this;
      }
      
      // required .org.sas04225.proto.QueryType queryType = 2;
      private org.sas04225.proto.RecognitionServerQueryProto.QueryType queryType_ = org.sas04225.proto.RecognitionServerQueryProto.QueryType.LOCATION_BASED_QUERY;
      public boolean hasQueryType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public org.sas04225.proto.RecognitionServerQueryProto.QueryType getQueryType() {
        return queryType_;
      }
      public Builder setQueryType(org.sas04225.proto.RecognitionServerQueryProto.QueryType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        queryType_ = value;
        onChanged();
        return this;
      }
      public Builder clearQueryType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        queryType_ = org.sas04225.proto.RecognitionServerQueryProto.QueryType.LOCATION_BASED_QUERY;
        onChanged();
        return this;
      }
      
      // required .org.sas04225.proto.QueryDataType queryDataType = 3;
      private org.sas04225.proto.RecognitionServerQueryProto.QueryDataType queryDataType_ = org.sas04225.proto.RecognitionServerQueryProto.QueryDataType.JPEG_IMAGE;
      public boolean hasQueryDataType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public org.sas04225.proto.RecognitionServerQueryProto.QueryDataType getQueryDataType() {
        return queryDataType_;
      }
      public Builder setQueryDataType(org.sas04225.proto.RecognitionServerQueryProto.QueryDataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        queryDataType_ = value;
        onChanged();
        return this;
      }
      public Builder clearQueryDataType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        queryDataType_ = org.sas04225.proto.RecognitionServerQueryProto.QueryDataType.JPEG_IMAGE;
        onChanged();
        return this;
      }
      
      // required uint32 location_id = 4;
      private int locationId_ ;
      public boolean hasLocationId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getLocationId() {
        return locationId_;
      }
      public Builder setLocationId(int value) {
        bitField0_ |= 0x00000008;
        locationId_ = value;
        onChanged();
        return this;
      }
      public Builder clearLocationId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        locationId_ = 0;
        onChanged();
        return this;
      }
      
      // required bytes queryData = 5;
      private com.google.protobuf.ByteString queryData_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasQueryData() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public com.google.protobuf.ByteString getQueryData() {
        return queryData_;
      }
      public Builder setQueryData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        queryData_ = value;
        onChanged();
        return this;
      }
      public Builder clearQueryData() {
        bitField0_ = (bitField0_ & ~0x00000010);
        queryData_ = getDefaultInstance().getQueryData();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.sas04225.proto.Query)
    }
    
    static {
      defaultInstance = new Query(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.sas04225.proto.Query)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_sas04225_proto_Query_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_sas04225_proto_Query_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034RecognitionServerQuery.proto\022\022org.sas0" +
      "4225.proto\"\257\001\n\005Query\022\022\n\nrequest_id\030\001 \002(\004" +
      "\0220\n\tqueryType\030\002 \002(\0162\035.org.sas04225.proto" +
      ".QueryType\0228\n\rqueryDataType\030\003 \002(\0162!.org." +
      "sas04225.proto.QueryDataType\022\023\n\013location" +
      "_id\030\004 \002(\r\022\021\n\tqueryData\030\005 \002(\014*8\n\tQueryTyp" +
      "e\022\030\n\024LOCATION_BASED_QUERY\020\000\022\021\n\rGENERAL_Q" +
      "UERY\020\001*5\n\rQueryDataType\022\016\n\nJPEG_IMAGE\020\000\022" +
      "\024\n\020FREAK_DESCRIPTOR\020\001B1\n\022org.sas04225.pr" +
      "otoB\033RecognitionServerQueryProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_sas04225_proto_Query_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_sas04225_proto_Query_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_sas04225_proto_Query_descriptor,
              new java.lang.String[] { "RequestId", "QueryType", "QueryDataType", "LocationId", "QueryData", },
              org.sas04225.proto.RecognitionServerQueryProto.Query.class,
              org.sas04225.proto.RecognitionServerQueryProto.Query.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
