// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LookupResult.proto

#ifndef PROTOBUF_LookupResult_2eproto__INCLUDED
#define PROTOBUF_LookupResult_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace org {
namespace sas04225 {
namespace proto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_LookupResult_2eproto();
void protobuf_AssignDesc_LookupResult_2eproto();
void protobuf_ShutdownFile_LookupResult_2eproto();

class LookupResult;
class DMatch;

// ===================================================================

class LookupResult : public ::google::protobuf::Message {
 public:
  LookupResult();
  virtual ~LookupResult();
  
  LookupResult(const LookupResult& from);
  
  inline LookupResult& operator=(const LookupResult& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const LookupResult& default_instance();
  
  void Swap(LookupResult* other);
  
  // implements Message ----------------------------------------------
  
  LookupResult* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LookupResult& from);
  void MergeFrom(const LookupResult& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint64 request_id = 1;
  inline bool has_request_id() const;
  inline void clear_request_id();
  static const int kRequestIdFieldNumber = 1;
  inline ::google::protobuf::uint64 request_id() const;
  inline void set_request_id(::google::protobuf::uint64 value);
  
  // repeated .org.sas04225.proto.DMatch matches = 2;
  inline int matches_size() const;
  inline void clear_matches();
  static const int kMatchesFieldNumber = 2;
  inline const ::org::sas04225::proto::DMatch& matches(int index) const;
  inline ::org::sas04225::proto::DMatch* mutable_matches(int index);
  inline ::org::sas04225::proto::DMatch* add_matches();
  inline const ::google::protobuf::RepeatedPtrField< ::org::sas04225::proto::DMatch >&
      matches() const;
  inline ::google::protobuf::RepeatedPtrField< ::org::sas04225::proto::DMatch >*
      mutable_matches();
  
  // @@protoc_insertion_point(class_scope:org.sas04225.proto.LookupResult)
 private:
  inline void set_has_request_id();
  inline void clear_has_request_id();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint64 request_id_;
  ::google::protobuf::RepeatedPtrField< ::org::sas04225::proto::DMatch > matches_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_LookupResult_2eproto();
  friend void protobuf_AssignDesc_LookupResult_2eproto();
  friend void protobuf_ShutdownFile_LookupResult_2eproto();
  
  void InitAsDefaultInstance();
  static LookupResult* default_instance_;
};
// -------------------------------------------------------------------

class DMatch : public ::google::protobuf::Message {
 public:
  DMatch();
  virtual ~DMatch();
  
  DMatch(const DMatch& from);
  
  inline DMatch& operator=(const DMatch& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const DMatch& default_instance();
  
  void Swap(DMatch* other);
  
  // implements Message ----------------------------------------------
  
  DMatch* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DMatch& from);
  void MergeFrom(const DMatch& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 distance = 1;
  inline bool has_distance() const;
  inline void clear_distance();
  static const int kDistanceFieldNumber = 1;
  inline ::google::protobuf::uint32 distance() const;
  inline void set_distance(::google::protobuf::uint32 value);
  
  // required uint64 trainIdx = 2;
  inline bool has_trainidx() const;
  inline void clear_trainidx();
  static const int kTrainIdxFieldNumber = 2;
  inline ::google::protobuf::uint64 trainidx() const;
  inline void set_trainidx(::google::protobuf::uint64 value);
  
  // @@protoc_insertion_point(class_scope:org.sas04225.proto.DMatch)
 private:
  inline void set_has_distance();
  inline void clear_has_distance();
  inline void set_has_trainidx();
  inline void clear_has_trainidx();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint64 trainidx_;
  ::google::protobuf::uint32 distance_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_LookupResult_2eproto();
  friend void protobuf_AssignDesc_LookupResult_2eproto();
  friend void protobuf_ShutdownFile_LookupResult_2eproto();
  
  void InitAsDefaultInstance();
  static DMatch* default_instance_;
};
// ===================================================================


// ===================================================================

// LookupResult

// required uint64 request_id = 1;
inline bool LookupResult::has_request_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LookupResult::set_has_request_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LookupResult::clear_has_request_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LookupResult::clear_request_id() {
  request_id_ = GOOGLE_ULONGLONG(0);
  clear_has_request_id();
}
inline ::google::protobuf::uint64 LookupResult::request_id() const {
  return request_id_;
}
inline void LookupResult::set_request_id(::google::protobuf::uint64 value) {
  set_has_request_id();
  request_id_ = value;
}

// repeated .org.sas04225.proto.DMatch matches = 2;
inline int LookupResult::matches_size() const {
  return matches_.size();
}
inline void LookupResult::clear_matches() {
  matches_.Clear();
}
inline const ::org::sas04225::proto::DMatch& LookupResult::matches(int index) const {
  return matches_.Get(index);
}
inline ::org::sas04225::proto::DMatch* LookupResult::mutable_matches(int index) {
  return matches_.Mutable(index);
}
inline ::org::sas04225::proto::DMatch* LookupResult::add_matches() {
  return matches_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::org::sas04225::proto::DMatch >&
LookupResult::matches() const {
  return matches_;
}
inline ::google::protobuf::RepeatedPtrField< ::org::sas04225::proto::DMatch >*
LookupResult::mutable_matches() {
  return &matches_;
}

// -------------------------------------------------------------------

// DMatch

// required uint32 distance = 1;
inline bool DMatch::has_distance() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DMatch::set_has_distance() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DMatch::clear_has_distance() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DMatch::clear_distance() {
  distance_ = 0u;
  clear_has_distance();
}
inline ::google::protobuf::uint32 DMatch::distance() const {
  return distance_;
}
inline void DMatch::set_distance(::google::protobuf::uint32 value) {
  set_has_distance();
  distance_ = value;
}

// required uint64 trainIdx = 2;
inline bool DMatch::has_trainidx() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DMatch::set_has_trainidx() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DMatch::clear_has_trainidx() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DMatch::clear_trainidx() {
  trainidx_ = GOOGLE_ULONGLONG(0);
  clear_has_trainidx();
}
inline ::google::protobuf::uint64 DMatch::trainidx() const {
  return trainidx_;
}
inline void DMatch::set_trainidx(::google::protobuf::uint64 value) {
  set_has_trainidx();
  trainidx_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace sas04225
}  // namespace org

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_LookupResult_2eproto__INCLUDED
