// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecognitionServerBackendInit.proto

#ifndef PROTOBUF_RecognitionServerBackendInit_2eproto__INCLUDED
#define PROTOBUF_RecognitionServerBackendInit_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace org {
namespace sas04225 {
namespace proto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_RecognitionServerBackendInit_2eproto();
void protobuf_AssignDesc_RecognitionServerBackendInit_2eproto();
void protobuf_ShutdownFile_RecognitionServerBackendInit_2eproto();

class RecognitionServerBackendInit;

// ===================================================================

class RecognitionServerBackendInit : public ::google::protobuf::Message {
 public:
  RecognitionServerBackendInit();
  virtual ~RecognitionServerBackendInit();
  
  RecognitionServerBackendInit(const RecognitionServerBackendInit& from);
  
  inline RecognitionServerBackendInit& operator=(const RecognitionServerBackendInit& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const RecognitionServerBackendInit& default_instance();
  
  void Swap(RecognitionServerBackendInit* other);
  
  // implements Message ----------------------------------------------
  
  RecognitionServerBackendInit* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RecognitionServerBackendInit& from);
  void MergeFrom(const RecognitionServerBackendInit& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint64 descriptor_count = 1;
  inline bool has_descriptor_count() const;
  inline void clear_descriptor_count();
  static const int kDescriptorCountFieldNumber = 1;
  inline ::google::protobuf::uint64 descriptor_count() const;
  inline void set_descriptor_count(::google::protobuf::uint64 value);
  
  // required string cache_path = 2;
  inline bool has_cache_path() const;
  inline void clear_cache_path();
  static const int kCachePathFieldNumber = 2;
  inline const ::std::string& cache_path() const;
  inline void set_cache_path(const ::std::string& value);
  inline void set_cache_path(const char* value);
  inline void set_cache_path(const char* value, size_t size);
  inline ::std::string* mutable_cache_path();
  inline ::std::string* release_cache_path();
  
  // @@protoc_insertion_point(class_scope:org.sas04225.proto.RecognitionServerBackendInit)
 private:
  inline void set_has_descriptor_count();
  inline void clear_has_descriptor_count();
  inline void set_has_cache_path();
  inline void clear_has_cache_path();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint64 descriptor_count_;
  ::std::string* cache_path_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_RecognitionServerBackendInit_2eproto();
  friend void protobuf_AssignDesc_RecognitionServerBackendInit_2eproto();
  friend void protobuf_ShutdownFile_RecognitionServerBackendInit_2eproto();
  
  void InitAsDefaultInstance();
  static RecognitionServerBackendInit* default_instance_;
};
// ===================================================================


// ===================================================================

// RecognitionServerBackendInit

// required uint64 descriptor_count = 1;
inline bool RecognitionServerBackendInit::has_descriptor_count() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RecognitionServerBackendInit::set_has_descriptor_count() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RecognitionServerBackendInit::clear_has_descriptor_count() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RecognitionServerBackendInit::clear_descriptor_count() {
  descriptor_count_ = GOOGLE_ULONGLONG(0);
  clear_has_descriptor_count();
}
inline ::google::protobuf::uint64 RecognitionServerBackendInit::descriptor_count() const {
  return descriptor_count_;
}
inline void RecognitionServerBackendInit::set_descriptor_count(::google::protobuf::uint64 value) {
  set_has_descriptor_count();
  descriptor_count_ = value;
}

// required string cache_path = 2;
inline bool RecognitionServerBackendInit::has_cache_path() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RecognitionServerBackendInit::set_has_cache_path() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RecognitionServerBackendInit::clear_has_cache_path() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RecognitionServerBackendInit::clear_cache_path() {
  if (cache_path_ != &::google::protobuf::internal::kEmptyString) {
    cache_path_->clear();
  }
  clear_has_cache_path();
}
inline const ::std::string& RecognitionServerBackendInit::cache_path() const {
  return *cache_path_;
}
inline void RecognitionServerBackendInit::set_cache_path(const ::std::string& value) {
  set_has_cache_path();
  if (cache_path_ == &::google::protobuf::internal::kEmptyString) {
    cache_path_ = new ::std::string;
  }
  cache_path_->assign(value);
}
inline void RecognitionServerBackendInit::set_cache_path(const char* value) {
  set_has_cache_path();
  if (cache_path_ == &::google::protobuf::internal::kEmptyString) {
    cache_path_ = new ::std::string;
  }
  cache_path_->assign(value);
}
inline void RecognitionServerBackendInit::set_cache_path(const char* value, size_t size) {
  set_has_cache_path();
  if (cache_path_ == &::google::protobuf::internal::kEmptyString) {
    cache_path_ = new ::std::string;
  }
  cache_path_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* RecognitionServerBackendInit::mutable_cache_path() {
  set_has_cache_path();
  if (cache_path_ == &::google::protobuf::internal::kEmptyString) {
    cache_path_ = new ::std::string;
  }
  return cache_path_;
}
inline ::std::string* RecognitionServerBackendInit::release_cache_path() {
  clear_has_cache_path();
  if (cache_path_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = cache_path_;
    cache_path_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace sas04225
}  // namespace org

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_RecognitionServerBackendInit_2eproto__INCLUDED
